/**
 * Programmatic access to the parsed card catalog.
 *
 * The catalog is generated by `pnpm --filter @hedgemony/spec parse` and
 * checked into the repo at `dist/cards.generated.json`.
 */
import type { CardCatalog } from "@hedgemony/shared";
import catalogJson from "../dist/cards.generated.json" with { type: "json" };

export const catalog: CardCatalog = catalogJson as CardCatalog;

export function getCard(typeAndId: string) {
  return catalog.byId[typeAndId];
}

// Original RAND Hedgemony sample cards (local study use only — see ORIGINAL/NOTICE.md).
export { CLASSIC_SAMPLE_CARDS, CLASSIC_SAMPLE_CARDS_BY_ID } from "./classic/cards";
